### PR TITLE
Add GO-variables to go generate environment

### PR DESCRIPTION
**Pull request by hacdias**
Related to caddyserver/caddydev#10

### CODE REVIEW

**Comment by abiosoft** [comment]
@hacdias You do not need to do this. You can always set the environment variables.

**Comment by hacdias** [comment]
I know I can, but I need them set when `go generate` runs so the code produced depends on the Arch and OS the user wants.

**Comment by hacdias** [comment]
For this hacdias/caddy-hugo#83

**Comment by hacdias** [comment]
Not needed anymore.

**Pull request closed without merging**
